services:
  - type: web
    name: telegram-forward-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: API_ID
        value: 123456
      - key: API_HASH
        value: your_api_hash_here
